name: Yarn build and Publish to another repo

on:
  workflow_dispatch:
  repository_dispatch:
    types: [dependency]
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Prepare static
        run: |
          git clone https://github.com/mirrorz-org/mirrorz-json-legacy.git static/json/json-legacy
          mv static/json/json-legacy/data static/json/legacy
          rm -rf static/json/json-legacy
          git clone https://github.com/mirrorz-org/mirrorz-json-site.git static/json/site
      - name: Prepare parser, config, oh-my-mirrorz
        run: |
          git clone https://github.com/mirrorz-org/mirrorz-parser.git src/parser
          git clone https://github.com/mirrorz-org/mirrorz-config.git src/config
          ln -s config/mirrorz.org.json src/config/config.json
          git clone https://github.com/mirrorz-org/oh-my-mirrorz.git scripts/oh-my-mirrorz
      - name: Prepare legacy
        run: |
          git clone https://github.com/mirrorz-org/mirrorz-legacy.git legacy
          ln -s ../ legacy/mirrorz
          ln -s ../src/config legacy/config
          ln -s ../static/json/legacy legacy/json-legacy
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Install legacy dependencies
        run: |
          cd legacy
          yarn --frozen-lockfile
          cd ..
      - name: oh-my-mirrorz build
        run: |
          sed -i "s/^VERSION.*/VERSION = '$(date +'%Y%m%d')'/g" scripts/oh-my-mirrorz/oh-my-mirrorz.py
          sed -i "s^mirrors = \[\]^mirrors = $(node -e 'console.log(JSON.stringify(require("./src/config/mirrors")))')^" scripts/oh-my-mirrorz/oh-my-mirrorz.py
      - name: Build
        run: |
          yarn build
          yarn ohmymirrorz_deploy
          yarn legacy_build
          mkdir -p drop
          tar -czf drop/dist.tar.gz dist
      - name: Upload dist package as artifact
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: drop/dist.tar.gz
          retention-days: 3
  screenshots:
    name: Visual diff
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: |
          yarn --frozen-lockfile
          npx playwright install-deps
          npx playwright install
      - name: Download dist package
        uses: actions/download-artifact@v2
        with:
          name: dist
      - name: Unzip dist package
        run: |
          tar xzf dist.tar.gz
      - name: Update snapshot baseline
        if: ${{ github.ref == 'refs/heads/master' }}
        run: |
          yarn test --update-snapshots
      - name: Upload screenshot baseline as artifacts
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: actions/upload-artifact@v2
        with:
          name: screenshot-baseline
          path: |
            tests/*-snapshots
      - name: Download baseline and take screenshots
        if: ${{ github.ref != 'refs/heads/master' }}
        run: |
          yarn download-snapshot-baseline snapshot-baseline.zip
          unzip -o snapshot-baseline.zip -d tests
          yarn test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload screenshot differences as artifacts
        if: ${{ github.ref != 'refs/heads/master' && always() }}
        uses: actions/upload-artifact@v2
        with:
          name: screenshots
          path: |
            tests/*-snapshots
            test-results
          retention-days: 3
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/master' }}
    needs:
      - build
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Download dist package
        uses: actions/download-artifact@v2
        with:
          name: dist
      - name: Commit and publish
        env: 
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          PUBLISH_REPOSITORY: ${{ secrets.PUBLISH_REPOSITORY }}
        run: |
          tar xzf dist.tar.gz
          remote_repo="https://x-access-token:${ACCESS_TOKEN}@github.com/${PUBLISH_REPOSITORY}.git"
          remote_branch="master"
          git_commit_id=$(git rev-parse --short HEAD)
          mkdir _site_remote && cd _site_remote
          git init
          git config user.name "Mirrorz Bot"
          git config user.email "bot@mirrorz.org"
          git remote add origin $remote_repo
          git pull origin $remote_branch
          git rm -rf .
          git clean -fxd
          cp -ar ../dist/*  ./
          touch .nojekyll
          git add .
          git commit -m "Github Action auto build for https://github.com/tuna/mirrorz/commit/${git_commit_id}" --allow-empty
          git push -u origin $remote_branch

